# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55db56a2667829841a14fcc94e04731948a5cddb6c1af64b00a648fe36ae4eda685b304dea35b1e1ac39cc679fb85a8f2a19a8b5e5e48bb90bd4b9ad40b822ec

test:
  secret_key_base: d6333cf0495bc1570e274e237e4c302d487ae6fac865587e76a013c6072b84e362dd65eb68e227d53407ef8d2587c3c6b517ec4cf8d331076bf700aaae7a842d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
